centos7 build init. Compatible with r21.11 branch
triton-inference-server/contrib pull request #5
Opened 2021-11-25 15:01 UTC by TrojanXu

Tested build: server + trt backend + python backend

2021-12-08 18:25 UTC, deadeyegoodwin requested changes

2021-12-08 18:25 UTC, deadeyegoodwin commented on centos_build/Dockerfile.centos7.min
> +ARG BASE_IMAGE=nvidia/cuda:11.3.0-cudnn8-devel-centos7
Copyright

2021-12-08 18:25 UTC, deadeyegoodwin commented on centos_build/Dockerfile.centos7.sdk
> +# Copyright (c) 2019-2021, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
It this is a new file then just use 2021. If you have been working on it since 2019 then can leave it as it is.

2021-12-08 18:25 UTC, deadeyegoodwin commented on centos_build/README.md
> +## How it works?
Copyright

2021-12-08 18:25 UTC, deadeyegoodwin commented on centos_build/README.md
> +## How it works?
You should add a initial section saying that this is centos build, and it is not officially supported, etc. You can just point to the section in the top-level readme that describes.

2021-12-08 18:25 UTC, deadeyegoodwin commented on centos_build/backend_images/tf1/Dockerfile.centos7.tf1
> +ARG BASE_IMAGE=tritonbuilder_centos7_min
copyright on all files

2022-02-27 07:56 UTC, TrojanXu commented
1. All files with copyrights. 
2. Notice about non-official support in centos_build/README.md
3. add support for onnxruntime
4. No need to use modified backend repos
5. track Triton version 22.02

2022-03-01 00:51 UTC, deadeyegoodwin approved these changes

2022-03-01 00:51 UTC, merged